### ISSUE TITLE
Not Compatible

### ISSUE THREAD

**Issue by siddantttt** [LectureDot/LectureAssign-vscode#1]
Command 'Extensions: Install from VSIX...' resulted in an error

Unable to install extension 'lecturedot.lecture-assign' as it is not compatible with VS Code '1.81.1'.

**Comment by vdv7** [comment]
This extension requires Visual Studio Code version 1.86.

If you are having trouble updating Visual Studio Code, it's probably because you are using a Mac, and have it in your Downloads folder, rather than in your Applications folder. 
- Move Visual Studio Code to the Applications folder, and then you should be able to update it.

After you have updated Visual Studio Code, you should be able to install the extension.

**Comment by vdv7** [comment]
This extension requires Visual Studio Code version 1.86.

If you are having trouble updating Visual Studio Code, it's probably because you are using a Mac, and have it in your Downloads folder, rather than in your Applications folder.

Move Visual Studio Code to the Applications folder, and then you should be able to update it.
After you have updated Visual Studio Code, you should be able to install the extension.
